# Generated by Django 3.1.7 on 2021-03-26 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='buy_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
